/* dsh-niao-message browser bundle — auto-generated by scripts/build-client.mjs; do not edit. Source: src/client.js */
window.__ModuleLoader__.load({
  id: "dsh-niao-message",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client.js
var client_exports = {};
__export(client_exports, {
  apply: () => apply
});
module.exports = __toCommonJS(client_exports);
var import_react = __toESM(require("react"), 1);
var ROUTE = "/api/dsh-niao-message";
var GROUPS = [
  {
    key: "abnormal",
    name: "\u5F02\u5E38\u7EC8\u6B62",
    note: "\u4EFB\u52A1\u672A\u80FD\u6B63\u5E38\u5B8C\u6210\uFF0C\u88AB\u8FEB\u5F02\u5E38\u7ED3\u675F",
    covers: ["\u4E0A\u4E0B\u6587\u8D85\u9650", "\u4EFB\u52A1\u963B\u585E", "\u4EFB\u52A1\u88AB\u4E2D\u6B62", "\u4EFB\u52A1\u88AB\u4E2D\u65AD", "\u56DE\u7B54\u51FA\u9519", "\u5DE5\u5177\u8C03\u7528\u5931\u8D25"]
  },
  {
    key: "waiting",
    name: "\u9700\u8981\u4F60\u64CD\u4F5C",
    note: "\u5BF9\u8BDD\u6682\u505C\uFF0C\u7B49\u5F85\u4F60\u7684\u786E\u8BA4\u3001\u6388\u6743\u6216\u6307\u793A\u540E\u624D\u80FD\u7EE7\u7EED",
    covers: ["\u7B49\u5F85\u7528\u6237\u786E\u8BA4\uFF08\u63D0\u95EE / \u662F\u5426\u7EE7\u7EED\uFF09", "\u7B49\u5F85\u7528\u6237\u6279\u51C6\uFF08\u6388\u6743\uFF09"]
  },
  {
    key: "success",
    name: "\u6B63\u5E38\u5B8C\u6210",
    note: "\u4EFB\u52A1\u987A\u5229\u6267\u884C\u5B8C\u6210",
    covers: ["\u56DE\u7B54\u5B8C\u6210", "\u5B50\u4EE3\u7406\u7ED3\u675F"]
  }
];
var SOUNDS = ["Glass", "Ping", "Basso", "Sosumi", "Submarine", "Hero", "Funk", "Pop", "default"];
var VAR_HINT = {
  abnormal: "\u53EF\u7528\u53D8\u91CF\uFF1A{reason}\uFF08\u5177\u4F53\u539F\u56E0\uFF09\u3001{name}\uFF08\u9519\u8BEF\u540D\uFF09\u3001{code}\uFF08\u9519\u8BEF\u7801\uFF09",
  waiting: "\u53EF\u7528\u53D8\u91CF\uFF1A{tool}\uFF08\u5DE5\u5177\u540D\uFF09\u2014\u2014\u7B49\u5F85\u6279\u51C6\u65F6",
  success: ""
};
async function rpc(action, payload) {
  try {
    const res = await fetch(ROUTE, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action, ...payload })
    });
    const data = await res.json();
    if (data && data.ok) return { ok: true, value: data.value };
    return { ok: false, error: data && data.error && data.error.message || `HTTP ${res.status}` };
  } catch (error) {
    return { ok: false, error: String(error && error.message ? error.message : error) };
  }
}
async function getConfig() {
  const res = await rpc("get-config");
  return res.ok ? res.value.config : null;
}
async function listApps() {
  const res = await rpc("list-apps");
  const a = res.ok && res.value && res.value.apps;
  return {
    harness: a && Array.isArray(a.harness) ? a.harness : [],
    browsers: a && Array.isArray(a.browsers) ? a.browsers : []
  };
}
function ToggleRow(props) {
  return import_react.default.createElement(
    "label",
    {
      className: "nio-msg-toggle",
      title: props.hint || ""
    },
    import_react.default.createElement("input", {
      type: "checkbox",
      checked: !!props.checked,
      onChange: (e) => props.onChange(e.target.checked)
    }),
    import_react.default.createElement("span", { className: "nio-msg-toggle-text" }, props.children)
  );
}
function ConfigPanel() {
  const [config, setConfig] = import_react.default.useState(null);
  const [apps, setApps] = import_react.default.useState({ harness: [], browsers: [] });
  const [saving, setSaving] = import_react.default.useState(false);
  const [saved, setSaved] = import_react.default.useState(false);
  const [testResult, setTestResult] = import_react.default.useState(null);
  const testBusy = import_react.default.useRef(false);
  import_react.default.useEffect(() => {
    let alive = true;
    getConfig().then((cfg) => {
      if (alive && cfg) setConfig(cfg);
    });
    listApps().then((names) => {
      if (alive) setApps(names);
    });
    return () => {
      alive = false;
    };
  }, []);
  const patchGroup = (key, field, value) => {
    setConfig((prev) => {
      if (!prev) return prev;
      const groups = { ...prev.groups || {} };
      groups[key] = { ...groups[key] || {}, [field]: value };
      return { ...prev, groups };
    });
    setSaved(false);
  };
  const patchClickOpen = (open) => {
    setConfig((prev) => {
      if (!prev) return prev;
      return { ...prev, click: { ...prev.click || {}, open } };
    });
    setSaved(false);
  };
  const save = async () => {
    if (!config) return;
    setSaving(true);
    const res = await rpc("set-config", { config });
    setSaving(false);
    if (res.ok) {
      setSaved(true);
      if (res.value.config) setConfig(res.value.config);
    } else {
      window.alert("\u4FDD\u5B58\u5931\u8D25\uFF1A" + res.error);
    }
  };
  const test = async () => {
    if (testBusy.current) return;
    testBusy.current = true;
    const res = await rpc("test");
    testBusy.current = false;
    setTestResult(res.ok ? { ok: true, text: "\u5DF2\u53D1\u9001\u6D4B\u8BD5\u901A\u77E5\uFF0C\u8BF7\u67E5\u770B\u901A\u77E5\u4E2D\u5FC3" } : { ok: false, text: "\u6D4B\u8BD5\u5931\u8D25\uFF1A" + res.error });
  };
  if (!config) {
    return import_react.default.createElement(
      "div",
      { className: "nio-msg" },
      import_react.default.createElement("p", { className: "nio-msg-note" }, "\u6B63\u5728\u52A0\u8F7D\u901A\u77E5\u914D\u7F6E\u2026")
    );
  }
  const root = import_react.default.createElement(
    "div",
    { className: "nio-msg" },
    /* 顶部操作行 */
    import_react.default.createElement(
      "div",
      { className: "nio-msg-top" },
      import_react.default.createElement("span", { className: "nio-msg-title" }, "\u901A\u77E5\u7BA1\u7406"),
      import_react.default.createElement(
        "div",
        { className: "nio-msg-top-actions" },
        import_react.default.createElement("button", { type: "button", className: "nio-msg-btn", onClick: test }, "\u6D4B\u8BD5\u901A\u77E5"),
        import_react.default.createElement(
          "button",
          { type: "button", className: "nio-msg-btn primary", onClick: save, disabled: saving || !config },
          saving ? "\u4FDD\u5B58\u4E2D\u2026" : "\u4FDD\u5B58"
        )
      )
    ),
    saved ? import_react.default.createElement(
      "div",
      { className: "nio-msg-testbar nio-msg-testbar-ok" },
      import_react.default.createElement("span", { className: "nio-msg-testbar-text" }, "\u5DF2\u4FDD\u5B58 \u2713\uFF08\u914D\u7F6E\u70ED\u52A0\u8F7D\u751F\u6548\uFF09"),
      import_react.default.createElement("button", { type: "button", className: "nio-msg-close", "aria-label": "\u5173\u95ED\u63D0\u793A", onClick: () => setSaved(false) }, "\xD7")
    ) : null,
    testResult ? import_react.default.createElement(
      "div",
      { className: "nio-msg-testbar " + (testResult.ok ? "nio-msg-testbar-ok" : "nio-msg-testbar-err") },
      import_react.default.createElement("span", { className: "nio-msg-testbar-text" }, testResult.text),
      import_react.default.createElement("button", { type: "button", className: "nio-msg-close", "aria-label": "\u5173\u95ED\u63D0\u793A", onClick: () => setTestResult(null) }, "\xD7")
    ) : null,
    /* 一、是否启用 */
    import_react.default.createElement(
      "div",
      { className: "nio-msg-block" },
      import_react.default.createElement("h3", { className: "nio-msg-block-title" }, "\u662F\u5426\u542F\u7528"),
      import_react.default.createElement(ToggleRow, {
        checked: config.enabled,
        onChange: (v) => {
          setConfig({ ...config, enabled: v });
          setSaved(false);
        },
        hint: "\u5173\u95ED\u540E\u6240\u6709\u573A\u666F\u90FD\u4E0D\u518D\u5F39\u7CFB\u7EDF\u901A\u77E5"
      }, "\u542F\u7528 macOS \u7CFB\u7EDF\u901A\u77E5")
    ),
    /* 二、通知行为 */
    import_react.default.createElement(
      "div",
      { className: "nio-msg-block" },
      import_react.default.createElement("h3", { className: "nio-msg-block-title" }, "\u901A\u77E5\u884C\u4E3A"),
      import_react.default.createElement(ToggleRow, {
        checked: !!config.allowRepeat,
        onChange: (v) => {
          setConfig({ ...config, allowRepeat: v });
          setSaved(false);
        },
        hint: "\u5F00\u542F\u540E\uFF0C\u5373\u4F7F\u901A\u77E5\u680F\u8FD8\u6709\u672A\u70B9\u51FB\u7684\u901A\u77E5\uFF0C\u65B0\u901A\u77E5\u4E5F\u4F1A\u7167\u5E38\u5F39\u51FA\uFF1B\u5173\u95ED\u65F6\uFF0C\u672A\u70B9\u51FB\u901A\u77E5\u5904\u7406\u524D\u65B0\u901A\u77E5\u4F1A\u88AB\u8DF3\u8FC7"
      }, "\u91CD\u590D\u901A\u77E5\uFF1A\u5B58\u5728\u672A\u70B9\u51FB\u7684\u901A\u77E5\u65F6\uFF0C\u6709\u65B0\u901A\u77E5\u4ECD\u7EE7\u7EED\u5F39\u51FA"),
      import_react.default.createElement(
        "p",
        { className: "nio-msg-scene-desc" },
        config.allowRepeat ? "\u5F53\u524D\u5DF2\u5F00\u542F\uFF1A\u5B58\u5728\u672A\u70B9\u51FB\u7684\u901A\u77E5\u65F6\uFF0C\u65B0\u901A\u77E5\u4ECD\u7167\u5E38\u5F39\u51FA" : "\u5F53\u524D\u5DF2\u5173\u95ED\uFF1A\u5B58\u5728\u672A\u70B9\u51FB\u7684\u901A\u77E5\u65F6\uFF0C\u65B0\u901A\u77E5\u5C06\u88AB\u8DF3\u8FC7\uFF0C\u907F\u514D\u5237\u5C4F"
      ),
      import_react.default.createElement(
        "label",
        { className: "nio-msg-field" },
        import_react.default.createElement("span", { className: "nio-msg-field-label" }, "\u70B9\u51FB\u901A\u77E5\u540E\u6253\u5F00"),
        import_react.default.createElement(
          "select",
          {
            className: "nio-msg-input nio-msg-select-open",
            value: config.click && config.click.open || "",
            onChange: (e) => patchClickOpen(e.target.value)
          },
          import_react.default.createElement("option", { value: "" }, "\u4E0D\u6253\u5F00\u4EFB\u4F55\u5E94\u7528"),
          // 保留旧值：用户此前保存过但已不在本机列表中的应用
          (() => {
            const cur = config.click && config.click.open || "";
            return cur && !apps.harness.includes(cur) && !apps.browsers.includes(cur) ? import_react.default.createElement("option", { key: "custom", value: cur }, cur) : null;
          })(),
          apps.harness.length ? import_react.default.createElement(
            "optgroup",
            { key: "harness", label: "DeepSeek Harness" },
            apps.harness.map((n) => import_react.default.createElement("option", { key: n, value: n }, n))
          ) : null,
          apps.browsers.length ? import_react.default.createElement(
            "optgroup",
            { key: "browsers", label: "\u6D4F\u89C8\u5668" },
            apps.browsers.map((n) => import_react.default.createElement("option", { key: n, value: n }, n))
          ) : null
        )
      ),
      import_react.default.createElement(
        "p",
        { className: "nio-msg-scene-desc" },
        "\u70B9\u51FB\u901A\u77E5\u6A2A\u5E45\u65F6\u6FC0\u6D3B\u7684\u5E94\u7528\uFF1B\u9009\u300C\u4E0D\u6253\u5F00\u4EFB\u4F55\u5E94\u7528\u300D\u65F6\uFF0C\u70B9\u51FB\u6A2A\u5E45\u4EC5\u6D88\u5931"
      )
    ),
    /* 三、通知分组（每组一个开关：开启后该组全部情况都通知） */
    import_react.default.createElement(
      "div",
      { className: "nio-msg-block" },
      import_react.default.createElement("h3", { className: "nio-msg-block-title" }, "\u901A\u77E5\u5206\u7EC4"),
      import_react.default.createElement("p", { className: "nio-msg-note" }, "\u628A\u53EF\u80FD\u51FA\u73B0\u901A\u77E5\u7684\u60C5\u51B5\u5206\u4E3A\u4E09\u5927\u7C7B\uFF0C\u5F00\u542F\u67D0\u7EC4\u540E\uFF0C\u8BE5\u7EC4\u8986\u76D6\u7684\u6240\u6709\u60C5\u51B5\u90FD\u4F1A\u5F39\u51FA\u901A\u77E5\uFF1A"),
      GROUPS.map((group) => {
        const g = config.groups && config.groups[group.key] || {};
        return import_react.default.createElement(
          "div",
          { key: group.key, className: "nio-msg-group" },
          import_react.default.createElement(
            "div",
            { className: "nio-msg-group-head" },
            import_react.default.createElement(ToggleRow, {
              checked: !!g.enabled,
              onChange: (v) => patchGroup(group.key, "enabled", v),
              hint: "\u5F00\u542F\u540E\uFF0C\u4EE5\u4E0B\u60C5\u51B5\u90FD\u4F1A\u5F39\u51FA\u901A\u77E5\uFF1A" + group.covers.join("\u3001")
            }, group.name),
            import_react.default.createElement("select", {
              className: "nio-msg-select",
              value: g.sound || "Glass",
              onChange: (e) => patchGroup(group.key, "sound", e.target.value),
              title: "\u63D0\u793A\u97F3"
            }, SOUNDS.map((s) => import_react.default.createElement("option", { key: s, value: s }, s)))
          ),
          import_react.default.createElement("p", { className: "nio-msg-group-desc" }, group.note),
          import_react.default.createElement("p", { className: "nio-msg-group-list" }, "\u8986\u76D6\uFF1A" + group.covers.join("\u3001")),
          import_react.default.createElement(
            "div",
            { className: "nio-msg-tpl-row" },
            import_react.default.createElement(
              "label",
              { className: "nio-msg-field" },
              import_react.default.createElement("span", { className: "nio-msg-field-label" }, "\u6807\u9898"),
              import_react.default.createElement("input", {
                className: "nio-msg-input",
                value: g.title || "",
                onChange: (e) => patchGroup(group.key, "title", e.target.value)
              })
            ),
            import_react.default.createElement(
              "label",
              { className: "nio-msg-field" },
              import_react.default.createElement("span", { className: "nio-msg-field-label" }, "\u6D88\u606F"),
              import_react.default.createElement("input", {
                className: "nio-msg-input",
                value: g.message || "",
                onChange: (e) => patchGroup(group.key, "message", e.target.value)
              })
            )
          ),
          VAR_HINT[group.key] ? import_react.default.createElement("p", { className: "nio-msg-group-desc" }, VAR_HINT[group.key]) : null
        );
      })
    )
  );
  return root;
}
var CSS = `
.nio-msg{display:flex;flex-direction:column;gap:14px;font-size:13px;line-height:1.5;color:var(--dsw-alias-label-primary)}
.nio-msg-top{display:flex;align-items:center;justify-content:space-between;gap:10px}
.nio-msg-title{font-size:15px;font-weight:600;color:var(--dsw-alias-label-primary)}
.nio-msg-top-actions{display:flex;gap:8px}
.nio-msg-btn{cursor:pointer;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);border-radius:6px;padding:5px 12px;font-size:12px;font-family:inherit}
.nio-msg-btn:hover{border-color:var(--dsw-alias-brand-primary);background:color-mix(in srgb, var(--dsw-alias-brand-primary) 12%, var(--dsw-alias-bg-layer-2))}
.nio-msg-btn:disabled{opacity:.55;cursor:default}
.nio-msg-btn.primary{border-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-label-primary);background:color-mix(in srgb, var(--dsw-alias-brand-primary) 14%, var(--dsw-alias-bg-layer-2))}
.nio-msg-btn.primary:hover{background:color-mix(in srgb, var(--dsw-alias-brand-primary) 24%, var(--dsw-alias-bg-layer-2))}
.nio-msg-testbar{display:flex;align-items:center;justify-content:space-between;gap:10px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;padding:8px 10px;font-size:12px;margin:0}
.nio-msg-testbar-ok{color:var(--dsw-alias-state-success-primary);border-color:color-mix(in srgb,var(--dsw-alias-state-success-primary) 35%,var(--dsw-alias-border-l1));background:color-mix(in srgb,var(--dsw-alias-state-success-primary) 8%,var(--dsw-alias-bg-layer-1))}
.nio-msg-testbar-err{color:var(--dsw-alias-state-error-primary);border-color:color-mix(in srgb,var(--dsw-alias-state-error-primary) 35%,var(--dsw-alias-border-l1));background:color-mix(in srgb,var(--dsw-alias-state-error-primary) 8%,var(--dsw-alias-bg-layer-1))}
.nio-msg-testbar-text{flex:1;min-width:0}
.nio-msg-close{cursor:pointer;flex:none;width:20px;height:20px;display:inline-flex;align-items:center;justify-content:center;border:none;border-radius:4px;background:transparent;color:inherit;font-size:14px;line-height:1;font-family:inherit;padding:0}
.nio-msg-close:hover{background:var(--dsw-alias-interactive-bg-hover)}
.nio-msg-block{display:flex;flex-direction:column;gap:8px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;padding:12px 14px;background:var(--dsw-alias-bg-layer-1)}
.nio-msg-block-title{margin:0;font-size:13px;font-weight:600;color:var(--dsw-alias-label-primary)}
.nio-msg-note{margin:0;font-size:12px;color:var(--dsw-alias-label-secondary)}
.nio-msg-toggle{display:flex;align-items:center;gap:8px;cursor:pointer;user-select:none}
.nio-msg-toggle input{width:15px;height:15px;accent-color:var(--dsw-alias-brand-primary);cursor:pointer}
.nio-msg-toggle-text{font-size:13px}
.nio-msg-scene-desc{margin:0;font-size:11px;color:var(--dsw-alias-label-secondary)}
.nio-msg-group{display:flex;flex-direction:column;gap:6px;padding:10px 12px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;background:color-mix(in srgb,var(--dsw-alias-bg-base) 55%,var(--dsw-alias-bg-layer-1))}
.nio-msg-group-head{display:flex;align-items:center;justify-content:space-between;gap:8px}
.nio-msg-group-desc{margin:0;font-size:11px;color:var(--dsw-alias-label-secondary)}
.nio-msg-group-list{margin:0;font-size:11px;color:var(--dsw-alias-label-secondary)}
.nio-msg-select{cursor:pointer;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);border-radius:6px;padding:3px 6px;font-size:12px;font-family:inherit}
.nio-msg-tpl-row{display:flex;gap:10px;flex-wrap:wrap;padding-top:2px}
.nio-msg-field{display:flex;flex-direction:column;gap:3px;flex:1;min-width:180px}
.nio-msg-field-label{font-size:11px;color:var(--dsw-alias-label-secondary)}
.nio-msg-input{box-sizing:border-box;width:100%;height:28px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base);border:1px solid var(--dsw-alias-border-l2);border-radius:6px;padding:0 8px;font-size:12px;font-family:inherit;outline:none}
.nio-msg-input:focus{border-color:var(--dsw-alias-brand-primary)}
.nio-msg-select-open{height:30px;cursor:pointer}
.nio-msg-select-open option,.nio-msg-select-open optgroup{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base)}
.nio-msg-nav-bell{display:inline-flex;align-items:center;justify-content:center;flex:none}
`;
var BELL_SVG = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>';
function patchSettingsNavIcon() {
  const buttons = document.querySelectorAll("button");
  for (const btn of buttons) {
    if (btn.dataset.niaoIconPatched) continue;
    let hasLabel = false;
    for (const span of btn.querySelectorAll("span")) {
      if (span.textContent && span.textContent.includes("\u901A\u77E5\u7BA1\u7406")) {
        hasLabel = true;
        break;
      }
    }
    if (!hasLabel) continue;
    const icon = btn.querySelector("svg");
    if (!icon) continue;
    btn.dataset.niaoIconPatched = "1";
    const bell = document.createElement("span");
    bell.className = "nio-msg-nav-bell";
    bell.setAttribute("aria-hidden", "true");
    bell.innerHTML = BELL_SVG;
    icon.replaceWith(bell);
  }
}
function apply(ctx) {
  ctx.effect(() => {
    const tag = document.createElement("style");
    tag.setAttribute("data-plugin", "dsh-niao-message");
    tag.setAttribute("data-plugin-css", "dsh-niao-message");
    tag.textContent = CSS;
    document.head.append(tag);
    return () => tag.remove();
  }, "dsh-niao-message: styles");
  ctx.effect(() => {
    const observer = new MutationObserver(patchSettingsNavIcon);
    observer.observe(document.body, { childList: true, subtree: true });
    patchSettingsNavIcon();
    return () => observer.disconnect();
  }, "dsh-niao-message: nav icon");
  const slots = ctx.get("slots");
  if (!slots) return;
  slots.inject("settings.section", () => slots.register(
    { name: "settings.section", id: "dsh-niao-message", order: 35, label: () => "\u901A\u77E5\u7BA1\u7406" },
    () => import_react.default.createElement(ConfigPanel, null)
  ));
}
    return module.exports;
  }
});
